apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonos-service
  namespace: vidalcasino
  labels:
    app: bonos-service
spec:
  replicas: 2
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: bonos-service
  template:
    metadata:
      labels:
        app: bonos-service
    spec:
      containers:
        - name: bonos
          image: 088950558880.dkr.ecr.us-east-1.amazonaws.com/casino/bonos:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          envFrom:
            - secretRef:
                name: casino-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/bonos/readyz
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/bonos/livez
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 10
